name: Build APK
on:
    push:
        branches:
            - master
jobs:
    publish:
        name: Install and build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: 16.x
            - name: Setup Expo and EAS
              uses: expo/expo-github-action@v7
              with:
                expo-version: 5.x
                eas-version: latest
            - name: Install dependecies
              run: yarn install
            - name: Login expo
              run: npx expo login -u ${{secrets.LOGIN}} -p ${{secrets.PASSWORD}} 
            - name: Build on EAS
              run: eas build -p android --profile development
